In [1]:
import pandas as pd
df=pd.read_csv('gender_submission.csv')
df.head()

   PassengerId  Survived
0          892         0
1          893         1
2          894         0
3          895         0
4          896         1

In [2]:
df.describe()

       PassengerId    Survived
count   418.000000  418.000000
mean   1100.500000    0.363636
std     120.810458    0.481622
min     892.000000    0.000000
25%     996.250000    0.000000
50%    1100.500000    0.000000
75%    1204.750000    1.000000
max    1309.000000    1.000000

In [5]:
df.isnull().sum()

PassengerId    0
Survived       0
dtype: int64

In [7]:
df.Survived.value_counts()

Survived
0    266
1    152
Name: count, dtype: int64

In [13]:
X=df[['PassengerId']]
y=df.Survived

In [14]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
x_scaled=ss.fit_transform(X)

In [16]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(x_scaled,y,test_size=0.2)

In [17]:
from sklearn.tree import DecisionTreeClassifier
tree=DecisionTreeClassifier()

In [18]:
tree.fit(X_train,y_train)

DecisionTreeClassifier()

In [19]:
tree.score(X_test,y_test)

0.47619047619047616

In [27]:
tree.predict(X_test)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1])

In [31]:
from sklearn.ensemble import BaggingClassifier
model=BaggingClassifier(
    estimator=DecisionTreeClassifier(),
    n_estimators=100,
    max_samples=0.8,
    oob_score=True
)

In [32]:
model.fit(X_train,y_train)

BaggingClassifier(estimator=DecisionTreeClassifier(), max_samples=0.8,
                  n_estimators=100, oob_score=True)

In [33]:
model.oob_score_

0.5209580838323353